complete -c dirbpy -s u -l url --description "This is the url to scan"
complete -c dirbpy -s f -l file --description "Input file with words"
complete -c dirbpy -s o -l online --description "Online dictionary"
complete -c dirbpy -s d -l directory --description "Input directory with dictionay"
complete -c dirbpy -s t -l thread -ends --description "Number of threads"
complete -c dirbpy -s c -l status_code --description "list of status code to accept"
complete -c dirbpy -s r -l remove_status_code --description "List of status code to remove"
complete -c dirbpy -s p -l proxy --description "URL of the proxy"
complete -c dirbpy -s i -l ignore --description "Ignore a directory"
complete -c dirbpy -s h -l help --description "Display help and exit"
complete -c dirbpy -s v -l version --description "Display version and exit"
complete -c dirbpy -l no_duplicate --description "Don't display the same URL twice"
complete -c dirbpy -s s -l save --description "Save the ouput in a file"
complete -c dirbpy -l hosts_file --description "File with a hosts list to scan"
